### ISSUE TITLE
Speedtest Error

### ISSUE THREAD

**Issue by finalbroadcast** [guarinogabriel/Mac-CLI#87]
It is totally possible that this is an issue with my system, but I've tired a few different things. Whenever I run mac speedtest I get this error. I've tried using both the root and the regular user account and neither seems to work. 
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'settings' of null
    at gotServers (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:522:20)
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:48:16
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:238:7
    at Parser.<anonymous> (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:499:16)
    at Parser.parseString (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:540:19)
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:236:5

**Comment by guarinogabriel** [comment]
Hi there!

Since this issue is directly related to the speed test library, I suggest you to open a PR on that project instead:
https://github.com/sindresorhus/speed-test

Best regards.
Gabriel
