### ISSUE TITLE
With all dependencies installed, `mac speedtest` returns an error

### ISSUE THREAD

**Issue by qbunt** [guarinogabriel/Mac-CLI#90]
Install script ran without issue, I'm running OS X 10.11.6. I get the following (what looks like) a Node error. I installed the speedtest-cli separately and ran that separately on the same system, that ran without issue.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'settings' of null
    at gotServers (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:522:20)
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:48:16
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:238:7
    at Parser.<anonymous> (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:494:16)
    at Parser.parseString (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:535:19)
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:236:5
```

**Comment by jasongwartz** [comment]
Also having this issue on 10.11.5 for the past few weeks, let me know if any debug info is needed

**Comment by guarinogabriel** [comment]
@qbunt @jasongwartz Thanks for reporting this issue. The speed test command has been fixed in the following commit: https://github.com/guarinogabriel/Mac-CLI/commit/90d69d536f6deda2f10c18217bcd9029ce23d566

**Comment by qbunt** [comment]
Thanks for the update here man, love the tool!
